const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = name => JSON.parse(fs.readFileSync(path.join(root, name), 'utf8'));
const fresh = (date, now) => typeof date === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(date) &&
  Number.isFinite(Date.parse(date)) && Date.parse(date) <= now && now - Date.parse(date) < 86400000;

function makeCatalog({preview = false, now = Date.now(), catalog = read('data/catalog.json'), approved = read('data/approved-content.json'), amazon = fs.existsSync(path.join(root,'data/amazon-content.json')) ? read('data/amazon-content.json') : {products:[]}} = {}) {
  const entries = new Map((approved.products || []).map(p => [p.asin, p]));
  for (const p of amazon.products || []) if (!entries.has(p.asin)) entries.set(p.asin, p);
  const products = catalog.products.map(p => {
    const base = {asin:p.asin, category:p.category, title:p.title, displayName:p.displayName, displaySpecs:p.displaySpecs};
    const content = entries.get(p.asin);
    if (content?.contentSource === 'publisher' && content.rightsConfirmed === true && typeof content.rightsReference === 'string' && content.rightsReference.trim()) {
      if (content.image && !/^assets\/products\/[a-zA-Z0-9_-]+\.(?:png|jpe?g|webp|avif)$/.test(content.image)) throw new Error(p.asin + ': Bild muss eine lokale Datei in assets/products sein.');
      if (content.image && !fs.existsSync(path.join(root,content.image))) throw new Error(p.asin + ': Bilddatei fehlt.');
      return {...base, contentSource:'publisher', image:content.image || '', rightsConfirmed:true, rightsReference:content.rightsReference,
        ...(fresh(content.updatedAt,now) && content.priceSource && content.vatIncluded === true ? {price:content.price, currency:'EUR', updatedAt:content.updatedAt} : {})};
    }
    if (content?.contentSource === 'amazon-creators-api' && fresh(content.updatedAt,now)) {
      return {...base, contentSource:content.contentSource, image:content.image, price:content.price, currency:content.currency, updatedAt:content.updatedAt, detailPageURL:content.detailPageURL};
    }
    if (preview) return {...base, contentSource:'local-preview', image:p.image, price:p.price, currency:'EUR', checkedAt:p.checkedAt, specs:p.specs};
    return base;
  });
  return {categories:catalog.categories, products};
}
function catalogScript(result) {
  // Escape HTML delimiters even though this is an external script.
  const json = value => JSON.stringify(value,null,2).replace(/</g,'\\u003c');
  return '// Generated by tools/generate-products.cjs.\nconst CATEGORIES = ' + json(result.categories) + ';\nconst PRODUCTS = ' + json(result.products) + ';\n';
}
module.exports = {makeCatalog, catalogScript, fresh};
